---
name: GuardDog

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  guarddog:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: "3.x"

      - name: Install GuardDog
        run: |
          sudo apt-get purge -y libgit2-1.7 libgit2-dev
          sudo apt-get install -y heimdal-dev
          curl -OL https://github.com/libgit2/libgit2/archive/refs/tags/v1.9.2.tar.gz && \
            tar xzf v1.9.2.tar.gz && \
            cd libgit2-1.9.2 && \
            ./ci/build.sh && \
            sudo make install
          pip install guarddog==2.7.0

      - name: Generate requirements.txt
        run: |
          python3 -mvenv venv
          . venv/bin/activate
          pip install -e .
          pip freeze | grep -v -f requirements-guarddog-ignore.txt | tee requirements.txt

      - name: Check requirements.txt
        run: |
          cat requirements.txt

      - name: Run guarddog
        run: |
          guarddog pypi verify requirements.txt --output-format sarif --exclude-rules repository_integrity_mismatch -x single_python_file > guarddog.sarif
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - name: View SARIF file
        run: |
          cat guarddog.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@f205ea1c3313d32999d8d6a48b4f6530d4437b38  # v4.37.4
        with:
          category: guarddog-builtin
          sarif_file: guarddog.sarif
