---
name: GuardDog

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  guarddog:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0

      - name: Set up Python UV
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1

      - name: Generate requirements.txt
        run: |
          python3 -mvenv venv
          . venv/bin/activate
          pip install -e .
          pip freeze | grep -v -f requirements-guarddog-ignore.txt | tee requirements.txt

      - name: Check requirements.txt
        run: |
          cat requirements.txt

      - name: Run guarddog
        run: |
          uvx guarddog pypi verify requirements.txt --output-format sarif --exclude-rules repository_integrity_mismatch -x single_python_file > guarddog.sarif
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - name: View SARIF file
        run: |
          cat guarddog.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2  # v4.38.2
        with:
          category: guarddog-builtin
          sarif_file: guarddog.sarif
