name: Release to PyPI
on:
  release:
    types: [published]
  push:
    tags:
      - v*.*.*

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: 3.14
      - name: Verify versioning
        run: |
          echo "$(poetry version -s)"
          echo "${GITHUB_REF#refs/tags/v}"
          [ "$(poetry version -s)" == "${GITHUB_REF#refs/tags/v}" ]
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
      - name: Build packages
        run: poetry build
      - name: Publish to test PyPI
        if: ${{ github.event_name == 'push' }}
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        if: ${{ github.event_name == 'release' }}
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
