---
name: Check URLs

on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@b643b43e2ac605e1475331c7b67247d242b7dce4  # tag=v0.0.34
      with:
        branch: main
        file_types: .md
        retry_count: 3
